version: 2

updates:
- package-ecosystem: "cargo"
  directory: "/link-for-later"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 15

- package-ecosystem: "cargo"
  directory: "/link-for-later-lambda"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 15
