name: development

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.74.0
                profile: minimal

            - name: Install Cargo Lambda
              run: pip install cargo-lambda==1.0.0

            - name: Build lambda
              run: cargo lambda build --release

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.74.0
                profile: minimal
                components: rustfmt, clippy

            - name: Format
              run: cargo fmt --all -- --check

            - name: Clippy
              run: cargo clippy --all-targets --all-features -- -D warnings
