name: development

on:
  push:
    branches: [ test-coverage ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.74.0
                profile: minimal

            - name: Release build
              run: cargo build --release

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.74.0
                profile: minimal
                components: rustfmt, clippy

            - name: Format
              run: cargo fmt --all -- --check

            - name: Clippy
              run: cargo clippy --all-targets --all-features -- -D warnings

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: 1.74.0
                profile: minimal

            - name: Unit Test
              run: cargo test --lib

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.10.0

            - name: Integration Test
              run: cargo test --test '*'
              env:
                RUST_TEST_THREADS: 1
                MONGODB_URI: "mongodb://localhost:27017/"
                MONGODB_DATABASE_NAME: "test"

            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov

            - name: Install rust-covfix
              run: |
                curl -L https://github.com/Kogia-sima/rust-covfix/releases/latest/download/rust-covfix-linux-x86_64.tar.xz |tar Jxf -
                mv rust-covfix-linux-x86_64/rust-covfix ./

            - name: Generate and fix code coverage
              run: |
                cargo llvm-cov --ignore-filename-regex "main|repository" --lcov --output-path lcov.info
                rust-covfix lcov.info -o lcov.info
              env:
                RUST_TEST_THREADS: 1
                MONGODB_URI: "mongodb://localhost:27017/"
                MONGODB_DATABASE_NAME: "test"
